### PR TITLE
add php 8.1 support to composer.json

### LINKED ISSUE #195: "Pdf::setCompressionQuality()"
Hello,

```
thrown in /var/www/clients/client8/web35/***/vendor/spatie/pdf-to-image/src/Pdf.php on line 108
[10-Apr-2022 20:30:08 Europe/Istanbul] PHP Fatal error:  Uncaught Error: Call to undefined method Spatie\PdfToImage\Pdf::setCompressionQuality()
```

If I use this tag `setCompressionQuality`, I get a 500 error.  What could be the reason for this?

Thank you.

### PR DESCRIPTION
**Pull request by lintaba**
fixes #195

### CODE REVIEW

**Comment by devinfd** [comment]
Please pull this PR in

**Comment by darviscommerce** [comment]
Why is this taking so long?

**Comment by patinthehat** [comment]
I believe this is unnecessary as the `^8.0` constraint means that `8.1` is also included (as is `8.2`, and so on).

@freekmurze Please correct me if I'm wrong, but I believe this PR can be closed without merging as the referenced issue (#195) is not related to this directly.

**Comment by darviscommerce** [comment]
> I believe this is unnecessary as the `^8.0` constraint means that `8.1` is also included (as is `8.2`, and so on).
> 
> @freekmurze Please correct me if I'm wrong, but I believe this PR can be closed without merging as the referenced issue (#195) is not related to this directly.

My comment is after testing en composer does not accept 8.1 with this setting.

**Pull request closed without merging**
