### PR TITLE
Update Pdf.php

### PR DESCRIPTION
**Pull request by BenjaminRehn**
Set transparent background to white..
*notTestet

### CODE REVIEW

**Comment by freekmurze** [comment]
Have you tested this?

**Comment by BenjaminRehn** [comment]
What do you think  means... *notTested  :8ball: 
;-) sorry don't have time to check all out and get an PDF etc.... but that should the correct, correction...

**Comment by BenjaminRehn** [comment]
http://php.net/manual/de/imagick.mergeimagelayers.php
Imagick Imagick::mergeImageLayers ( int $layer_method )

i think this is correct... i can test it this evening / tomorrow 
sorry

**Comment by whoisthecoon** [comment]
Hi,

The fix doesn't work but using `mergeImageLayers` is the right thing to do. It's just not correctly used. It should be : 

```php
$imagick = $imagick->mergeImageLayers(\Imagick::LAYERMETHOD_FLATTEN);
```
Tested on 180 PDF files.

I can do a PR if needed.

**Comment by farwel** [comment]
As stated here: https://laracasts.com/discuss/channels/laravel/spatie-media-library-some-pdf-thumbnails-render-with-black-background?page=0

It should be:

`$imagick = $imagick->mergeImageLayers(\Imagick::LAYERMETHOD_FLATTEN);`

As mergeImageLayers returns a new imagick object instead of modifying the current one.

**Comment by nikmauro** [comment]
The library render the png images with white background and no wih transparent. I have use multiple PDF samples.

**Pull request merged**
