### PR TITLE
Remove pingImage usage, load number of pages lazily

### PR DESCRIPTION
**Pull request by bobvandevijver**
Fixed version of #187.

### CODE REVIEW

**Comment by freekmurze** [comment]
Do all the tests pass when you run them locally?

**Comment by freekmurze** [comment]
I'm getting this test output with this code

```
  • Tests\PdfTest > it will correctly return the number of pages in pdf file
  Failed asserting that 0 matches expected 3.
```

**Comment by bobvandevijver** [comment]
I will check, the tests won't run locally at all at this time...

**Comment by bobvandevijver** [comment]
Here it is completely different...

```
  • Tests\PdfTest > it will correctly return the number of pages in pdf file
  Failed asserting that 6 matches expected 3.
```

It looks like the pingImage causes the PDF file to be loaded twice on my machine, so removing it completely would solve it.

**Comment by bobvandevijver** [comment]
(btw, I tested it back when I originally opened this PR, and there the `pingImage` did work correctly when executed twice...)

**Comment by bobvandevijver** [comment]
@freekmurze Any progress on this one?

**Pull request closed without merging**
