### PR TITLE
support php 8

### PR DESCRIPTION
**Pull request by Nielsvanpach**

### CODE REVIEW

**Comment by Nielsvanpach** [comment]
Not that I know. I can only suggest to sponsor Danack, the maintainer.
https://github.com/Imagick/imagick/issues/271

**Comment by mokhosh** [comment]
Thank you, he seems to be too angry to answer that at the moment 😄

**Comment by mokhosh** [comment]
The Imagick retard is making this package unusable. Can we consider using an alternative?
Also https://github.com/nextcloud/server/issues/13099

**Comment by freekmurze** [comment]
We will stick with Imagick and hope the maintainer tags a PHP 8 compatible version soon.

For now, you can build a PHP 8 compatible version from the master branch.
https://freek.dev/1845-building-the-imagick-php-extension-from-master

**Pull request merged**
